// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVozxrrql7ywN8FzHRksqQTHZP_JiYQw',
    appId: '1:1086026492144:web:6bf61172e89923b59f3a35',
    messagingSenderId: '1086026492144',
    projectId: 'tormentapp456238',
    authDomain: 'tormentapp456238.firebaseapp.com',
    storageBucket: 'tormentapp456238.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPHCRjFTa74wVqEYzzi-nQOf_oWE_x2U',
    appId: '1:1086026492144:android:5c83f2931038b17e9f3a35',
    messagingSenderId: '1086026492144',
    projectId: 'tormentapp456238',
    storageBucket: 'tormentapp456238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-mgqgZok3rodWhTUoz0YtsEO5BExAXs',
    appId: '1:1086026492144:ios:e648425f9a3e2da79f3a35',
    messagingSenderId: '1086026492144',
    projectId: 'tormentapp456238',
    storageBucket: 'tormentapp456238.appspot.com',
    iosClientId: '1086026492144-sjh2lobj6mbijskpqmbclrccv0lhrqbg.apps.googleusercontent.com',
    iosBundleId: 'com.egemenerdm.torment.torment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-mgqgZok3rodWhTUoz0YtsEO5BExAXs',
    appId: '1:1086026492144:ios:e648425f9a3e2da79f3a35',
    messagingSenderId: '1086026492144',
    projectId: 'tormentapp456238',
    storageBucket: 'tormentapp456238.appspot.com',
    iosClientId: '1086026492144-sjh2lobj6mbijskpqmbclrccv0lhrqbg.apps.googleusercontent.com',
    iosBundleId: 'com.egemenerdm.torment.torment',
  );
}
